### ISSUE TITLE
Disconnecting and reconnecting results in `undefined` being sent from `MessageBuffer`

### ISSUE THREAD

**Issue by amsross** [zenmoto/bunyan-tcp#4]
I don't recall how the exact math works out, but this value [`i % this.messageMax`](https://github.com/zenmoto/bunyan-tcp/blob/master/index.js#L39) is not guaranteed to be less than `oldBuffer.length` which results in `undefined` applied to `cb`. This only pops up if you connect, send logs, disconnect, reconnect, and attempts to `drain` the `MessageBuffer`.

Using `Array.shift`/`Array.push` instead of comparing `mod`s of counts and lengths resolves this.

**Comment by amsross** [comment]
I have a branch with a test and fix for this, but I'm not able to push it right now. Here's a diff for the test to expose the issue:

```
diff --git a/index.js b/index.js
index eaac596..e2d33ff 100644
--- a/index.js
+++ b/index.js
@@ -136,4 +136,3 @@ function createBunyanStream(args) {
 }
 
 module.exports.createBunyanStream = createBunyanStream;
-module.exports.MessageBuffer = MessageBuffer;
diff --git a/test/test.js b/test/test.js
index 58f7584..68d5ab1 100644
--- a/test/test.js
+++ b/test/test.js
@@ -270,7 +270,7 @@ describe("Disconnect", function() {
 
       }).finally(function() {server.close();});
     });
-  });
+  })
 });
 
 describe("Transforms", function() {
@@ -298,33 +298,4 @@ describe("Transforms", function() {
       }).finally(function() {server.close();});
     });
   });
-});
-
-describe("MessageBuffer", function() {
-  it("should drain all of the messages up to the buffer size", function() {
-    var messageBuffer = new bunyanTcp.MessageBuffer(5);
-
-    messageBuffer.add(1)
-    messageBuffer.add(2)
-    messageBuffer.add(3)
-    messageBuffer.add(4)
-    messageBuffer.add(5)
-
-    var values = []
-
-    messageBuffer.drain(function (value) {
-      values.push(value);
-    });
-
-    messageBuffer.add(6)
-    messageBuffer.add(7)
-    messageBuffer.add(8)
-    messageBuffer.add(9)
-
-    messageBuffer.drain(function (value) {
-      values.push(value);
-    });
-
-    expect(values).to.deep.equal([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]);
-  });
-});
+})
```

**Comment by zenmoto** [comment]
@amsross Sorry I didn't see this- the alert got lost in my sea of GitHub notifications. To be honest, I haven't used Bunyan, much less a TCP output from it in some time. Would you be interested in taking it over?

**Comment by amsross** [comment]
@zenmoto that's understandable. Seeing as how this project seems pretty low-touch, I'll volunteer to pick up the maintenance on it.
